spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25433/test
    username: pg
    password: postgres
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        remove-existing-vector-store-table: true   # 测试建议 true，生产别开
        schema-name: public
        table-name: vector_store
        index-type: HNSW                           # 默认往往就是 HNSW
        dimensions: 768
    model:
      embedding: ollama
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text



logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.boot.autoconfigure: INFO